services:
  homework-2-backend:
    image: homework-2-backapp
      
  homework-2-frontend:
    image: homework-2-frontapp
    ports:
    - 8080:8080
    environment: 
      BACK_URL: "http://homework-2-backend:8080"